# Generated by Django 5.0.1 on 2024-01-17 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedPost', to='network.post')),
                ('likingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
